[WIP] Dialogs defined as a Style w/ ControlTemplate and Icons
MahApps/MahApps.Metro pull request #4209
Opened 2021-11-13 10:19 UTC by Time2Code0

Changed the Dialogs from a UserControl to a Style with ControlTemplate (see #4168) this also opens the option of adding Icons to it as suggested in #2282 (still WIP).

- [ x]  Define Dialogs as a Style
- [ ] Display Icons

P.S: This is my first time working on an open source project, so let me know what I can improve/do better next time :)

Greetings

2021-11-13 13:25 UTC, punker76 reviewed
Thx you for your contribution! Please look at my first comments. Your changes are looking good.

2021-11-13 13:25 UTC, punker76 commented on src/global.json
> -}
Please revert this deleted file. thx

2021-11-13 13:25 UTC, punker76 commented on src/MahApps.Metro/Controls/Dialogs/InputDialog.cs
> +﻿using System;
Please add these lines here, like in the other `*.cs` files :
```csharp
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

```

2021-11-13 13:25 UTC, punker76 commented on src/MahApps.Metro/Controls/Dialogs/LoginDialog.cs
> +﻿using System;
Please add these lines here, like in the other `*.cs` files :
```csharp
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

```

2021-11-13 13:25 UTC, punker76 commented on src/MahApps.Metro/Controls/Dialogs/MessageDialog.cs
> +﻿using System;
Please add these lines here, like in the other `*.cs` files :
```csharp
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

```

2021-11-13 13:25 UTC, punker76 commented on src/MahApps.Metro/Controls/Dialogs/ProgressDialog.cs
> +﻿using System.Threading;
Please add these lines here, like in the other `*.cs` files :
```csharp
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

```

2021-11-13 14:01 UTC, Time2Code0 commented
> Thx you for your contribution! Please look at my first comments. Your changes are looking good.

Done. Added the gobal.json again (I deleted it on my local machine because it could not resolve the .Net SDK version and I was too lazy to install the correct one) and the missing License Text again.

Greetings

2021-11-16 17:39 UTC, Time2Code0 commented
Good evening,

I have added the Icon Presenter to the other dialogs. The current status is shown in the picture below. Let me know what you think about it.

Greeting

![IconDIalog](https://user-images.githubusercontent.com/47297708/142036950-60102784-a384-4c65-a6a4-99ef8258ccc8.PNG)

2021-11-19 18:15 UTC, punker76 requested changes
It looks really good. Can you take a look to my new comments? And the external Dialogs doesn't close anymore by using the buttons (but could be a bug before too). Thx

2021-11-19 18:15 UTC, punker76 commented on src/MahApps.Metro/Themes/Dialogs/LoginDialog.xaml
> +            </Grid>-->
I think this can be removed.

2021-11-19 18:15 UTC, punker76 commented on src/MahApps.Metro/Controls/Dialogs/ProgressDialog.cs
> +
Is it not better to move this to the base class? Because it is used in each derived class. So a user can use this in a custom dialog too. WDYT?

2021-11-19 18:15 UTC, punker76 commented on src/MahApps.Metro/Controls/Dialogs/MessageDialog.cs
> +        }
Is it not better to move this to the base class? Because it is used in each derived class. So a user can use this in a custom dialog too. WDYT?

2021-11-19 18:15 UTC, punker76 commented on src/MahApps.Metro/Controls/Dialogs/LoginDialog.cs
> +        }
Is it not better to move this to the base class? Because it is used in each derived class. So a user can use this in a custom dialog too. WDYT?

2021-11-19 18:15 UTC, punker76 commented on src/MahApps.Metro/Controls/Dialogs/InputDialog.cs
>              this.Icon = this.DialogSettings.Icon;
Is it not better to move this to the base class? Because it is used in each derived class. So a user can use this in a custom dialog too. WDYT?

2021-11-20 10:00 UTC, Time2Code0 commented
You are absolutely correct that the Icon and IconTemplate should be a Proeprty in the BaseMetroDialog. As far as I can tell, the problem with the external Dialog is that OnApplyTemplate is executed after the WaitForButtonPressAsync method, for this reason the controls are null and the EventHandle is not applied to them.

Greetings

2021-11-20 23:02 UTC, punker76 requested changes

2021-11-22 21:25 UTC, punker76 commented on src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindow.xaml
> +                 ShowTitleBar="{Binding ShowMyTitleBar, Mode=TwoWay}"
@Time2Code0 Can you remove this too?

2021-11-23 16:49 UTC, Time2Code0 commented on src/MahApps.Metro.Samples/MahApps.Metro.Demo/MainWindow.xaml
> +                 ShowTitleBar="{Binding ShowMyTitleBar, Mode=TwoWay}"
Of course. I thought I had removed it, but as you can see, I missed it.

2021-11-24 22:03 UTC, punker76 approved these changes

2021-11-24 22:29 UTC, merged

2021-11-24 22:29 UTC, punker76 commented
@Time2Code0 your changes have been merged, thanks for your contribution 👍