Fixed bug - Missing FallbackValue values in binding for MahApps.Style…
MahApps/MahApps.Metro pull request #4241
Opened 2022-01-02 14:00 UTC by oriches

…s.MenuItem causing 'System.Windows.Data.Inforamtion 10:...' messages to be generated. This causes performance problems when the controls are unloaded from the view or when DataContext is set to null.

## Describe the changes you have made to improve this project

XAML binding performance bug - missing FallbackValue values causes WPF information messages to be generated

## Unit test

No unit tests - changes to XAML only

## Additional context

N/A
 
## Closed Issues

N/A

2022-01-02 17:12 UTC, punker76 commented
@oriches Thx for your contribution. Can you show where or when this issue happens? If you have an example then it makes easier to understand. Thx

2022-01-03 13:37 UTC, oriches commented
Background:

I orginally notice when using MahApps.Dialogs with a fade out transition there was a slight UI freeze / judder on the fading out transition when the dialog was showing an ItemsControl (less than 10 items), similiarly I also notice when clearing a DataGrid hosted in the normal window there was longer than expected UI freeze when clearing the rows from the grid - in this example we are talking 75 columns, and less than 300 rows (financial spreadsheet kind of view)

I use a little trick with a DispatcherTimer to observe when the Dispatcher thread is overloaded (UI freezes for more than 500ms) and could see in debug mode values greater than 500ms...

Trying to understand the delay when clearing repeative templates from the view lead me down the route of inspecting the visual tree using Snoop, and from there enabling the Debug Listener for the Information level, at which point lots of repeative 'System.Windows.Data.Inforamtion 10:' messages are produced when clearing items from ItemsControls or DataGrid - this does depend on the Template one has defined obiviously, I also saw issues with ComboBox, ListView etc.

I have reported one for TextBox before, I found this one when using TextBox in the ItemTemplate for the message dialog - fixing this removed the UI stutter on the fade out transition - see `[here](https://github.com/MahApps/MahApps.Metro/issues/4217)`

I started to look for this issue in other places and found quite a few more, but for these I didn't raise a bug, I just fixed by redefining the MahApp Styles in my application. But then I thought why not contribute back (I love MahApps :)).

Regarding above issue:

On another view I have a DataGrid where when the data is refreshed everything is rebuilt - columns & rows, and each column has right-click context menu associated to it. When I enabled WPF tracing I started to see the issue with the horizontal & vertical alignments.

Now you could argue this is not a big issue when not using tabulated data but for me it is an issue becuase it slows performance and degrades the use of transitions for dialogs, flyouts etc...

Thoughts?

2022-01-03 18:45 UTC, timunie commented
Hi @oriches,

 Interesting observation. I also noticed some performance "issues" with grouping and sorting in a `DataGrid`. I wonder if this is related. 

@punker76 if I find the time in the next days I'll test this PR in my App and see if it has a noticeable benefit.

Happy coding 
Tim

2022-01-03 23:04 UTC, oriches commented
Just to be clear, this PR only affects menu items, it will affect all menu items in an app if they use the default menu style.ThanksOllieOn 3 Jan 2022 18:45, Tim ***@***.***> wrote:
Hi @oriches,
Interesting observation. I also noticed some performance "issues" with grouping and sorting in a DataGrid. I wonder if this is related.
@punker76 if I find the time in the next days I'll test this PR in my App and see if it has a noticeable benefit.
Happy coding
Tim

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-01-24 07:20 UTC, punker76 requested changes

2022-01-24 07:20 UTC, punker76 commented on src/MahApps.Metro/Styles/Controls.MenuItem.xaml
> +        <Setter Property="HorizontalContentAlignment" Value="{Binding HorizontalContentAlignment, RelativeSource={RelativeSource AncestorType={x:Type ItemsControl}}, FallbackValue={x:Static Horizonta
I would set the fallback to `HorizontalAlignment.Left` because it's the default of `HorizontalContentAlignment`.

2022-01-24 07:20 UTC, punker76 commented on src/MahApps.Metro/Styles/Controls.MenuItem.xaml
> +        <Setter Property="VerticalContentAlignment" Value="{Binding VerticalContentAlignment, RelativeSource={RelativeSource AncestorType={x:Type ItemsControl}}, FallbackValue={x:Static VerticalAlign
I would set the fallback to `VerticalAlignment.Center` because it's the default of `VerticalContentAlignment` of the MenuBase (ContextMenu).

2022-01-24 09:53 UTC, oriches commented
agreed

2022-01-24 11:49 UTC, punker76 approved these changes

2022-01-24 11:49 UTC, merged

2022-01-24 11:50 UTC, punker76 commented
@oriches your changes have been merged, thanks for your contribution 👍