Reorder and change all default styles with keys;
MahApps/MahApps.Metro pull request #4290
Opened 2022-04-21 04:20 UTC by ye4241

## Describe the changes you have made to improve this project

- Sort ResourceDictionary and Styles by name in Generic.xaml and Controls.xaml;
- Add all x:Key for all controls and  add default styles in Generic.xaml and Controls.xaml;

## Unit test

None.

## Additional context

- Remove political content from README.md;

## Closed Issues

None.

2022-04-21 04:21 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/MahApps/MahApps.Metro?pullRequest=4290) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/MahApps/MahApps.Metro?pullRequest=4290) before we can accept your contribution.<br/><br/>:x: ye4241 [sign now](https://cla.dotnetfoundation.org/MahApps/MahApps.Metro?pullRequest=4290)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/MahApps/MahApps.Metro?pullRequest=4290) it.</sub>

2022-04-21 08:07 UTC, Nuklon commented
Remove political content from README.md;
> ye4241, China

What a surprise.

2022-04-21 10:48 UTC, punker76 requested changes

2022-04-21 10:48 UTC, punker76 commented on readme.md
> -
Please revert this change. Thx

2022-04-22 09:48 UTC, ye4241 commented on readme.md
> -
Reverted.

2022-05-07 08:36 UTC, closed without merging